/**
 * Barrel re-export — keeps all existing `import { … } from "@/services/api"`
 * working while the actual code lives in focused domain modules.
 */

// Shared utilities
export {
  API_BASE,
  API_URL,
  getImageUrl,
  handleResponse,
  authFetch,
  userAuthFetch,
} from "./client";

// Products, categories, reviews, uploads
export {
  type ProductsResponse,
  type ProductInput,
  type Review,
  fetchProducts,
  fetchProduct,
  fetchCategories,
  createCategory,
  updateCategory,
  deleteCategory,
  createProduct,
  updateProduct,
  updateProductStock,
  deleteProduct,
  uploadImage,
  uploadImages,
  publicUploadImage,
  getProductReviews,
  submitProductReview,
  fetchAdminReviews,
  deleteReview,
} from "./products";

// Orders & payments
export {
  type OrderItem,
  type ShippingInfo,
  type CreateOrderPayload,
  type CreateOrderResponse,
  type Order,
  createOrder,
  createAdminOrder,
  fetchGuestOrders,
  trackOrder,
  updateOrderPaymentMethod,
  fetchAllOrders,
  fetchOrderById,
  updateOrderStatus,
  initializePayment,
  verifyPayment,
  cancelOrder,
} from "./orders";

// User auth, verification, profile
export {
  type ShippingAddress,
  type User,
  type UserLoginResponse,
  userRegister,
  userLogin,
  userLogout,
  getUserMe,
  getUserOrders,
  verifyEmail,
  resendVerificationEmail,
  updateUserProfile,
  userChangePassword,
} from "./auth";

// Admin auth, users, reports, activity logs
export {
  type AdminUser,
  type LoginResponse,
  type KPIData,
  type AdminStats,
  type AnalyticsData,
  type TopProduct,
  type StockDistribution,
  type OrderStatusDistribution,
  type ActivityLog,
  type RegionalData,
  type RecentOrder,
  type AdminUserListItem,
  type AdminUserDetails,
  type AdminUserStats,
  type AdminUsersPagination,
  type AdminUsersResponse,
  type AdminUserDetailsResponse,
  type CustomersResponse,
  type CustomerDetailsResponse,
  type AIAnalyticsSummary,
  type AIAnalyticsTotals,
  type GlobalSearchResult,
  adminLogin,
  adminChangePassword,
  adminLogout,
  getAdminMe,
  updateAdminProfile,
  getAdminStats,
  fetchDashboardStats,
  fetchAnalytics,
  fetchTopProducts,
  fetchStockDistribution,
  fetchOrderStatusDistribution,
  fetchRecentOrders,
  fetchActivityLogs,
  fetchRegionalReport,
  fetchAdminUsers,
  fetchCustomers,
  registerAdminUser,
  updateAdminUserRole,
  fetchAdminUserDetails,
  fetchCustomerDetails,
  deleteAdminUser,
  adminResetStaffPassword,
  adminToggleStaffActive,
  deleteCustomer,
  adminResetUserPassword,
  adminToggleUserActive,
  fetchAIAnalyticsSummary,
  globalAdminSearch,
} from "./admin";

// Support tickets, consultations, inquiries
export {
  type SupportTicket,
  type Consultation,
  type Inquiry,
  type NewsletterSubscriber,
  type NewsletterCampaign,
  createTicket,
  fetchSupportTickets,
  updateTicketStatus,
  scheduleConsultation,
  fetchConsultations,
  updateConsultationStatus,
  rescheduleConsultation,
  deleteConsultation,
  sendContactMessage,
  fetchInquiries,
  updateInquiryStatus,
  deleteInquiry,
  subscribeToNewsletter,
  fetchNewsletterSubscribers,
  updateNewsletterSubscriberStatus,
  updateNewsletterSubscriberContact,
  sendNewsletterCampaign,
  fetchNewsletterCampaigns,
  processScheduledNewsletterCampaigns,
  deleteNewsletterCampaign,
  cancelNewsletterCampaign,
} from "./support";

// Team, projects, testimonials, site stats
export {
  type TeamMember,
  type Project,
  type Testimonial,
  type SiteStat,
  fetchTeam,
  createTeamMember,
  updateTeamMember,
  deleteTeamMember,
  fetchProjects,
  fetchProjectById,
  createProject,
  updateProject,
  deleteProject,
  fetchTestimonials,
  fetchAdminTestimonials,
  createTestimonial,
  submitPublicTestimonial,
  updateTestimonial,
  deleteTestimonial,
  syncTrustpilotTestimonials,
  fetchStats,
  createStat,
  updateStat,
  deleteStat,
} from "./content";
