// Generates src/styles/tokens.css from design/system/tokens.json.
// The JSON is the source of truth; never edit the generated CSS by hand.
// Run with `yarn tokens` after the design system changes.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(resolve(root, "design/system/tokens.json"), "utf8"));
const outFile = resolve(root, "src/styles/tokens.css");

const colors = tokens.color.tokens;
const primitives = new Map(
  colors.filter((t) => typeof t.value === "string").map((t) => [t.name, t.value]),
);

// Semantic values may reference a primitive as "{navy-700}"; resolve to var().
function colorValue(value) {
  const ref = /^\{([a-z0-9-]+)\}$/.exec(value);
  if (!ref) return value;
  if (!primitives.has(ref[1])) throw new Error(`Unknown colour reference ${value}`);
  return `var(--${ref[1]})`;
}

const semantic = colors.filter((t) => typeof t.value === "object");
const light = semantic.map((t) => `  --${t.name}: ${colorValue(t.value.light)};`);
const dark = semantic.map((t) => `  --${t.name}: ${colorValue(t.value.dark)};`);

const scalar = (group) => group.tokens.map((t) => `  --${t.name}: ${t.value};`);
const shadowLight = tokens.shadow.tokens.map((t) => `  --sh-${t.name}: ${t.value.light};`);
const shadowDark = tokens.shadow.tokens.map((t) => `  --sh-${t.name}: ${t.value.dark};`);

const families = Object.entries(tokens.type.families).map(
  ([name, stack]) => `  --font-${name}-stack: ${stack.replaceAll('"', "'").replace(/^'([^']+)'/, "'$1 Variable', '$1'")};`,
);

const typeStyles = tokens.type.groups.flatMap((group) =>
  group.styles.flatMap((s) => {
    const lines = [
      `  --text-${s.name}: ${s.fontSize};`,
      `  --text-${s.name}--line-height: ${s.lineHeight};`,
      `  --text-${s.name}--font-weight: ${s.fontWeight};`,
    ];
    if (s.letterSpacing) lines.push(`  --text-${s.name}--letter-spacing: ${s.letterSpacing};`);
    return lines;
  }),
);

// Tailwind utilities (bg-page, text-ink, border-border, ...) read these.
const themeColors = [...primitives.keys(), ...semantic.map((t) => t.name)].map(
  (name) => `  --color-${name}: var(--${name});`,
);

const css = `/* Generated by scripts/build-tokens.mjs from design/system/tokens.json. Do not edit. */

:root {
${[...primitives].map(([name, value]) => `  --${name}: ${value};`).join("\n")}

${light.join("\n")}

${scalar(tokens.spacing).join("\n")}
${shadowLight.join("\n")}
${families.join("\n")}
}

/* The site follows the visitor's system setting. */
@media (prefers-color-scheme: dark) {
  :root {
${dark.map((l) => "  " + l).join("\n")}
${shadowDark.map((l) => "  " + l).join("\n")}
  }
}

/* Theme-dependent values: utilities read the live variables. */
@theme inline {
${themeColors.join("\n")}

  --font-display: var(--font-display-stack);
  --font-text: var(--font-text-stack);
  --font-mono: var(--font-mono-stack);
${tokens.shadow.tokens.map((t) => `  --shadow-${t.name.replace(/^shadow-/, "")}: var(--sh-${t.name});`).join("\n")}
}

/* Fixed values: radius-*, max-w-max, max-w-measure and text-* styles. */
@theme {
${tokens.radius.tokens.map((t) => `  --${t.name}: ${t.value};`).join("\n")}
  --container-max: ${tokens.container.tokens.find((t) => t.name === "container-max").value};
  --container-measure: ${tokens.container.tokens.find((t) => t.name === "measure").value};

${typeStyles.join("\n")}
}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, css);
console.log(`Wrote ${outFile}`);
